language: python

python:
    - "2.7"

env:
    - TOXENV=py26-django14
    - TOXENV=py26-django15
    - TOXENV=py26-django16
    - TOXENV=py27-django14
    - TOXENV=py27-django15
    - TOXENV=py27-django16
    - TOXENV=py27-django-dev
    #- TOXENV=py33-django15
    #- TOXENV=py33-django16
    #- TOXENV=py33-django-dev

install:
    - pip install tox --use-mirrors

script:
    - tox

branches:
  only:
    - master

matrix:
  allow_failures:
    - env: TOXENV=py33-django15
    - env: TOXENV=py33-django16
    - env: TOXENV=py33-django-dev

after_success:
  - coverage report
  - pip install --quiet --use-mirrors python-coveralls
  - coveralls
